### ISSUE TITLE
Typo for Thursday in WeeklyGenerator.scala

### ISSUE THREAD

**Issue by sachinhejip** [cetic/rts-gen#5]
(Firstly - thank you for this great library) - 

Typo for "thursday" in 
https://github.com/cetic/TSimulus/blob/master/src/main/scala/be/cetic/tsimulus/generators/primary/WeeklyGenerator.scala#L36

The issue is aggravated by the fact that the error reported has the right spelling for "thursday" - java.util.NoSuchElementException: key not found: thursday

(I can fix it (although my Scala skills can be generously described only as "beginner") - I wasn't sure what the impact is on any existing configurations e.g. - should the existing typo be retained and another mapping with the correct spelling added?)

**Comment by officialdharam** [comment]
Bumped into this today... I guess adding a new mapping is better. Just wondering if the count of the mapping is considered while preparing the output, The values in the points might not give right correlation.

**Comment by mgoeminne** [comment]
Thank you for your report, and sorry for the late answer, I missed the two first email alerts.
@sachinhejip feel free to submit a pull request fixing the typo, it should be easy whatever your Scala skills :) Otherwise I'll fix it myself.

I prefer to replace the typo by the correct day name, otherwise the library will have to support 8 day names for historical reasons…

Adding both spelling (i.e., introducing a new mapping) would not be a problem, however, since only the datetime constants are used internally.
