### ISSUE TITLE
Configuration to omit days in week?

### ISSUE THREAD

**Issue by StephenOTT** [cetic/rts-gen#7]
Assume a weekly time series and I want to generate series Monday through Friday. No values for weekends. And I want to generate noise for Monday through Friday.

**Comment by mgoeminne** [comment]
v0.1.16 ( 06648ca6e43914bcc92c4e84f7afbe548ad54905 ) aims to support datetime based time series. In particular, there is a DayOfWeek generator that generates the day (as an integer) of the timestamp associated with a time series.

Combine a [Now generator](https://tsimulus.readthedocs.io/en/latest/generators.html#now-generator) with a [DayOfWeek generator](https://tsimulus.readthedocs.io/en/latest/generators.html#dayofweek-generator), and then use it with a [conditional generator](https://tsimulus.readthedocs.io/en/latest/generators.html#conditional-time-series) in order to modify the shape of your signal -- for instance by adding a noise time series only when the day of week correspond to a specific value. 

[TSimulus-cli v1.16](https://github.com/cetic/tsimulus-cli/releases/tag/v1.16) is based on the TSimumus-lib v0.1.16.
